/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class XBRZNative */

#ifndef _Included_XBRZNative
#define _Included_XBRZNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     XBRZNative
 * Method:    ScaleandSetTexImage
 * Signature: (I[BIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jpcsp_graphics_RE_XBRZNative_ScaleandSetTexImage__I_3BIIIIIII
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     XBRZNative
 * Method:    ScaleandSetTexImage
 * Signature: (I[IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jpcsp_graphics_RE_XBRZNative_ScaleandSetTexImage__I_3IIIIIIII
  (JNIEnv *, jclass, jint, jintArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     XBRZNative
 * Method:    ScaleandSetTexImage
 * Signature: (I[SIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jpcsp_graphics_RE_XBRZNative_ScaleandSetTexImage__I_3SIIIIIII
  (JNIEnv *, jclass, jint, jshortArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     XBRZNative
 * Method:    ScaleandSetTexImage
 * Signature: (I[FIIIIIII)V
 */
JNIEXPORT void JNICALL Java_jpcsp_graphics_RE_XBRZNative_ScaleandSetTexImage__I_3FIIIIIII
  (JNIEnv *, jclass, jint, jfloatArray, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
